plat_index:
    path:     /
    defaults: { _controller: "PlatBundle:Plat:index" }
    methods:  GET

plat_show:
    path:     /{id}/show
    defaults: { _controller: "PlatBundle:Plat:show" }
    methods:  GET


plat_edit:
    path:     /{id}/edit
    defaults: { _controller: "PlatBundle:Plat:edit" }
    methods:  [GET, POST]

plat_delete:
    path:     /{id}/delete
    defaults: { _controller: "PlatBundle:Plat:delete" }
    methods:  DELETE
