<?php

namespace Plat\PlatBundle\Repository;

/**
 * IngrediantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngrediantRepository extends \Doctrine\ORM\EntityRepository
{
}
