<?php

namespace Plat\PlatBundle\Repository;

/**
 * plt_ingrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plt_ingrRepository extends \Doctrine\ORM\EntityRepository
{
}
